export enum UserRole {
  RENTER = 'RENTER',
  LISTER = 'LISTER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NOT_SUBMITTED = 'NOT_SUBMITTED',
}

export enum BookingStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
  CLOSED = 'CLOSED',
}

export enum DepositStatus {
  HELD = 'HELD',
  RELEASED_TO_RENTER = 'RELEASED_TO_RENTER',
  RELEASED_TO_LISTER = 'RELEASED_TO_LISTER',
  PARTIALLY_RELEASED = 'PARTIALLY_RELEASED',
  DISPUTED = 'DISPUTED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum PaymentProvider {
  PAYHERE = 'PAYHERE',
  IPAY = 'IPAY',
  STRIPE = 'STRIPE',
}

export enum ConditionPhotoParty {
  OWNER = 'OWNER',
  RENTER = 'RENTER',
}

export enum ConditionPhotoType {
  PICKUP = 'PICKUP',
  RETURN = 'RETURN',
}

export enum DisputeStatus {
  RAISED = 'RAISED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  ESCALATED = 'ESCALATED',
  CLOSED = 'CLOSED',
}

export enum DisputeOutcome {
  FAVOUR_RENTER = 'FAVOUR_RENTER',
  FAVOUR_LISTER = 'FAVOUR_LISTER',
  SPLIT = 'SPLIT',
  NO_ACTION = 'NO_ACTION',
}

export enum BadgeCategory {
  PAID = 'PAID',
  EARNED = 'EARNED',
}

export enum BadgeType {
  TOP_RATED = 'TOP_RATED',
  VERIFIED_ITEM = 'VERIFIED_ITEM',
  FAST_RESPONDER = 'FAST_RESPONDER',
  SPONSORED = 'SPONSORED',
  FEATURED = 'FEATURED',
}

export enum ListingStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum SubscriptionTier {
  BASIC = 'BASIC',
  PRO = 'PRO',
  PREMIUM = 'PREMIUM',
}

export enum CancellationTier {
  FULL_REFUND = 'FULL_REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  NO_REFUND = 'NO_REFUND',
  NO_SHOW = 'NO_SHOW',
}

export enum DepositAuditAction {
  HELD = 'HELD',
  RELEASED_TO_RENTER = 'RELEASED_TO_RENTER',
  RELEASED_TO_LISTER = 'RELEASED_TO_LISTER',
  PARTIALLY_RELEASED = 'PARTIALLY_RELEASED',
  DISPUTED = 'DISPUTED',
  SYSTEM_AUTO_RELEASED = 'SYSTEM_AUTO_RELEASED',
  ADMIN_MANUAL_RELEASE = 'ADMIN_MANUAL_RELEASE',
}

export enum NotificationType {
  BOOKING_REQUEST = 'BOOKING_REQUEST',
  BOOKING_APPROVED = 'BOOKING_APPROVED',
  BOOKING_DECLINED = 'BOOKING_DECLINED',
  RENTAL_STARTING = 'RENTAL_STARTING',
  RENTAL_ENDING = 'RENTAL_ENDING',
  DEPOSIT_RELEASED = 'DEPOSIT_RELEASED',
  DISPUTE_RAISED = 'DISPUTE_RAISED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  REVIEW_REQUESTED = 'REVIEW_REQUESTED',
  ID_VERIFICATION_APPROVED = 'ID_VERIFICATION_APPROVED',
  ID_VERIFICATION_REJECTED = 'ID_VERIFICATION_REJECTED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  REFERRAL_CONVERTED = 'REFERRAL_CONVERTED',
}

export enum PropertyType {
  APARTMENT = 'APARTMENT',
  HOUSE = 'HOUSE',
  VILLA = 'VILLA',
  COMMERCIAL = 'COMMERCIAL',
  LAND = 'LAND',
}

export enum PropertyStatus {
  VACANT = 'VACANT',
  OCCUPIED = 'OCCUPIED',
  MAINTENANCE = 'MAINTENANCE',
}
